In [2]:
import numpy as np

In [6]:
x = np.random.rand(400,10)
x.shape

(400, 10)

In [15]:
ref_idx = 5
# I want to pull ref_idx: ref_idx+3 rows, and columns 0,1,5,6 and have these be variables
col_indices = [0, 1, 5, 6]

num_save = 9
row_indices = slice(ref_idx, ref_idx + num_save)
x[row_indices, col_indices]

array([[0.47459054, 0.52963794, 0.67947333, 0.27928769],
       [0.08704871, 0.10957723, 0.99165632, 0.74027365],
       [0.73884299, 0.58434582, 0.34756089, 0.24085842],
       [0.93545974, 0.4237181 , 0.7278739 , 0.43620638],
       [0.46170423, 0.94501366, 0.10219583, 0.37373419],
       [0.60027473, 0.24212718, 0.90233682, 0.42782408],
       [0.00556939, 0.09754909, 0.32094892, 0.97081033],
       [0.27284595, 0.7241298 , 0.29134992, 0.78060706],
       [0.09641507, 0.13984003, 0.36923011, 0.28623455]])

In [30]:
y = np.random.rand(500,10)
y[0:26,:]

array([[6.56631693e-01, 3.89097485e-01, 9.61815350e-03, 7.08422596e-01,
        3.81452006e-01, 8.96363345e-01, 5.25559476e-01, 8.99910159e-01,
        8.35987986e-01, 7.70375793e-01],
       [1.67353304e-01, 8.59134419e-01, 8.89698137e-01, 5.58102873e-01,
        2.14180062e-01, 2.04749259e-01, 1.96517345e-01, 9.32663226e-02,
        2.86395761e-01, 2.10545486e-02],
       [4.67775986e-01, 4.01707011e-01, 7.60025981e-01, 2.92475892e-01,
        4.88706145e-01, 4.83776910e-01, 6.87976112e-01, 2.77616870e-02,
        4.14757992e-01, 6.52918423e-01],
       [4.89610781e-01, 8.66387964e-01, 3.07915421e-01, 4.72442571e-01,
        1.55153046e-01, 2.89014470e-02, 4.83421966e-01, 7.93804046e-01,
        9.55818955e-01, 8.46993109e-01],
       [7.25491190e-01, 2.71403800e-01, 1.66311719e-01, 8.98287942e-01,
        5.90835707e-01, 6.51025123e-01, 7.52534630e-01, 7.10589115e-01,
        7.16881655e-01, 2.99772904e-01],
       [7.38137330e-01, 6.28474354e-01, 1.02299764e-01, 7.73016305e-01,
   

In [31]:
# get [0:26:4,:] indices as a variable
indices = slice(0,26,4)
pos_indices = [0,1,5,6]
y[indices, pos_indices]



array([[0.65663169, 0.38909748, 0.89636335, 0.52555948],
       [0.72549119, 0.2714038 , 0.65102512, 0.75253463],
       [0.68513877, 0.84064003, 0.39617386, 0.73347728],
       [0.09994474, 0.71966845, 0.00531303, 0.9842878 ],
       [0.90655802, 0.25545784, 0.77851196, 0.65386684],
       [0.44585449, 0.69138861, 0.31524573, 0.11983197],
       [0.73413285, 0.00147869, 0.60845806, 0.62338055]])

In [40]:
length = len(range(*indices.indices(26)))
print(length)

7
